### ISSUE TITLE
ChromeOS mouse driver

### ISSUE THREAD

**Issue by hugegreenbug** [jquagga/AcerC720#1]
I just wanted to point you to my port of the ChromeOS mouse driver. It works much better than the synaptic driver for the touchpad. https://github.com/hugegreenbug/xf86-input-cmt

**Comment by jquagga** [comment]
Thanks!

I haven't had a chance to play around with it yet, but I updated the README for this repo to point to the cmt driver.  Hopefully I can get a chance to play around with it next week or weekend!

**Comment by joebonrichie** [comment]
I've got it working in Arch now, thanks.

I've quickly set up some instructions for getting it to work
https://github.com/joebonrichie/xf86-input-cmt

The packages in the AUR should be updated soon, only problem being the conf files doesn't get automatically copied for the right device but this could be solved with Arch chromebook page documentation.

Let me know if you get it working

**Comment by hugegreenbug** [comment]
Great! When I get a chance to try Arch, I will try it out. Some more things
you might me interested are:

1. My distro-mods repo: https://github.com/hugegreenbug/distro-mods
2. My site: distroshare.com for anyone to share distributions. I and 3
others have several distributions pre-made for the Acer C720 with the
chromeOS mouse driver and all the other fixes in my distro-mods repo. No
Arch yet :(.

Hugh

**Comment by hugegreenbug** [comment]
Btw, I'm using your icc file in my new distros. Thanks for that! It really
makes a difference, but I needed to adjust the colors a bit:
https://github.com/hugegreenbug/distro-mods/blob/master/acerc720_common/usr/local/bin/apply-icc.sh

Hugh

**Comment by jquagga** [comment]
You're very welcome!

I think when I generated the icc file I kept the panel at its native white balance.  It usually gives the panel a little more to work with, but you have to adapt to the different color temp (or adjust as you did).  I don't think the panel is going to win any awards regardless though.  It's functional, but not very pretty.  

I've been running the latest grsecurity kernel on arch and not having many problems of late, other than chromium consuming all of the ram on the system and locking it up.  I have to work out a way to limit that; possibly docker.  But overall it's an impressive little system.  I'm glad it has a real Haswell and not a Bay Trail like the newer models.  My NAS has a Bay Trail and it's ok, but doesn't have the horsepower.
